# Generated by Django 4.2.3 on 2023-07-10 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(6)])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(11)])),
                ('firstname', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('lastName', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='/(84|0[3|5|7|8|9])+([0-9]{8})\\b/g')])),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
