# Generated by Django 4.2.3 on 2023-07-10 15:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginAndRegister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('lastName', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='/(84|0[3|5|7|8|9])+([0-9]{8})\\b/g')])),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
