# Generated by Django 4.2.3 on 2023-07-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('VT', 'Vòng Tay'), ('DC', 'Dây Chuyền'), ('TD', 'Trầm Đốt'), ('NT', 'Nụ Trầm')], max_length=2)),
                ('status', models.CharField(choices=[('CH', 'Còn Hàng'), ('HH', 'Hết Hàng'), ('YC', 'Yêu Cầu')], max_length=2)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='item/')),
            ],
        ),
    ]
